### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by harshavardhan7209**
Nice Game Bro!!!

### CODE REVIEW

**Comment by paardhiv** [comment]
i made it tho

**Comment by paardhiv** [comment]
It was one of the project

**Comment by paardhiv** [comment]
S Paardhiv’s project, "KANGAROO IN JUNGLE-1"

**Comment by harshavardhan7209** [comment]
Dude, please make it usable on phone too

**Comment by harshavardhan7209** [comment]
You can use bootstrap for that

**Comment by paardhiv** [comment]
Sure will work

**Comment by paardhiv** [comment]
Will work on it*
I don't use github much i did not even know that you can talk in it

**Pull request closed without merging**
